export const userActions = {
  GET_LIST_USER: "GET_LIST_USER",
  GET_LIST_USER_SUCCESS: "GET_LIST_USER_SUCCESS",
  GET_ME: "GET_ME",
  GET_ME_SUCCESS: "GET_ME_SUCCESS",
  UPDATE_USER_INFO: "UPDATE_USER_INFO",
  UPDATE_USER_PROFILE: "UPDATE_USER_PROFILE",
  ADD_USER: "ADD_USER",
  DELETE_USER: "DELETE_USER",
  IMPORT_USER: "IMPORT_USER",
  GET_LIST_ADMIN: "GET_LIST_ADMIN",
  GET_LIST_ADMIN_SUCCESS: "GET_LIST_ADMIN_SUCCESS",
};

export const permissionActions = {
  GET_LIST_PERMISSION: "GET_LIST_PERMISSION",
  GET_LIST_PERMISSION_SUCCESS: "GET_LIST_PERMISSION_SUCCESS",
  ADD_PERMISSION: "ADD_PERMISSION",
  DELETE_PERMISSION: "DELETE_PERMISSION",
};
