export const userActions = {
  GET_LIST_USER: "GET_LIST_USER",
  GET_LIST_USER_SUCCESS: "GET_LIST_USER_SUCCESS",
  GET_ME: "GET_ME",
  GET_ME_SUCCESS: "GET_ME_SUCCESS",
  UPDATE_USER_INFO: "UPDATE_USER_INFO",
  UPDATE_USER_PROFILE: "UPDATE_USER_PROFILE"
};
